matrix:
  include:
    - language: node_js
      node_js: "10"
      before_install:
        - cd $TRAVIS_BUILD_DIR/src/PracticePlans.FrontEnd/
    - language: chsarp
      mono: none
      dotnet: 2.1.401
      before_install:
        - cd $TRAVIS_BUILD_DIR/src/PracticePlans.WebApi/
      script:
        - dotnet restore
        - dotnet build

