matrix:
  include:
    - language: node_js
      node_js: "10"
      before_install:
        - cd $TRAVIS_BUILD_DIR/src/PracticePlans.FrontEnd/
    - language: csharp
      mono: none
      dotnet: 2.1.402
      script:
        - dotnet restore src/PracticePlans.WebApi/PracticePlans.WebApi.csproj
        - dotnet build src/PracticePlans.WebApi/PracticePlans.WebApi.csproj

