export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';

export const LOAD_PRACTICEPLANS_SUCCESS = 'LOAD_PRACTICEPLANS_SUCCESS';
export const CREATE_PRACTICEPLAN_SUCCESS = 'CREATE_PRACTICEPLAN_SUCCESS';
export const UPDATE_PRACTICEPLAN_SUCCESS = 'UPDATE_PRACTICEPLAN_SUCCESS';
